--- 
title: "R Cookbook for Structural Equation Modeling"
author: "Ge Jiang"
date: "QUERIES, University of Illinois at Urbana-Champaign"
site: bookdown::bookdown_site
---

# Course

Structural Equation Modeling (SEM) is a general class of multivariate techniques that models relationships between latent variables and observed variables (“measurement models”) and relationships among latent variables (“structural models”) simultaneously. Students will learn the theoretical background of SEM as well as the techniques using programming language R. Topics covered in this class include mediation/moderation model; confirmatory factor analysis; model fit evaluation; multi-group SEM; latent growth modeling; MTMM model; and SEM with categorical variables. 4 graduate hours. No professional credit. Prerequisite: EPSY 580 and EPSY 581, or equivalents.

This site is supposed to serve as a repository for R codes used in lab sessions of a graduate-level method course EPSY 579. 

*Disclaimer: Opinions are my own and not the views of my employer.
